#!/bin/sh -x

run_app_dev() {

    cd /opt/mozilla-iot-gateway-dev

    echo "node version"
    node --version

    echo "npm version"
    npm --version

    echo "Starting gateway ..."
    npm start

}

run_app_dev > /tmp/mozilla-iot-run-dev.log 2>&1 &
